import json
import os

class ReportDao(object):
	"""
		ReportDao for handling report data generated by analyzing HIIT MON workouts.
		Dao might be quite the stretch.  This just dumps data into a file and then 
			pulls the whole file when asked.
	"""
	def __init__(self, path):
		super(ReportDao, self).__init__()
		self._path = path
		
	def create(self, data):
		with open(self._path, 'a') as handle:
			json.dump(data, handle)
			handle.write("\n")

	def getAll(self):
		with open(self._path, 'r+') as handle:
			return [json.loads(line) for line in handle.read().split("\n") if len(line.strip()) > 1]